// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/workspaces/nuxt/node_modules/.pnpm/@sidebase+nuxt-auth@0.10.1_magicast@0.3.5_next-auth@4.21.1_next@15.3.3_@babel+core@7.27_b5bde235cc0ee66429811ba436c3ef77/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
